name: startr
version: 0.0.1
description: Clones template snippets into project.
author: Damon Douglas <douglas.damon@gmail.com>
homepage: https://github.com/damondouglas/startr.dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.13 <0.13.0'
dependencies:
  path: '>=1.3.9 <2.0.0'
  args: '>=0.13.4 <0.14.0'
  ansicolor: '>=0.0.9 <0.1.0'
  random_string: '>=0.0.1 <0.1.0'
  git: '>=0.4.4+2 <0.5.0'
